name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}


jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "5.1.1"
          - "4.14.2"
      fail-fast: false

    name: Ocaml version - ${{ matrix.ocaml-compiler }} - ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: setup
        run: |
          opam install . --deps-only --with-test --with-doc --yes

      - name: build library 
        run: opam exec -- dune build lib

      - name: test
        run: opam exec -- dune exec --instrument-with bisect_ppx --force -- _build/default/test/test_zarr.exe -runner sequential -ci true

      - name: Upload code coverage report
        run: opam exec -- bisect-ppx-report send-to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Docs
        run: opam exec -- dune build @doc

      - name: Upload API Docs artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: docs
          path: ./_build/default/_doc/_html

      - name: Deploy API Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html
